name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install root dependencies
        run: npm ci

      - name: Install server dependencies
        run: npm ci
        working-directory: server

      - name: Typecheck and build
        run: |
          npm run typecheck
          npm run build

      - name: API smoke test
        run: npm run -s smoke

      - name: Install Playwright browsers
        uses: microsoft/playwright-github-action@v1

      - name: Run Playwright E2E
        run: npx playwright test --reporter=html
        env:
          # Base URL and upload dir can be overridden as needed
          E2E_BASE_URL: http://localhost:1420

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
